version: '3.8'

networks:
  my-net:

services:
  mysql:
    image: mysql:latest
    container_name: justdabsql
    volumes:
      - data:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "just_dab_db"
    ports:
      - "3333:3306"
    networks:
      - my-net

  backend:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: just_dab_app
    restart: always
    environment:
      DATABASE_URL: "jdbc:mysql://justdabsql:3306/just_dab_db"
      DATABASE_PASSWORD: "password"
    ports:
      - "8081:8080"
    networks:
      - my-net

volumes:
  data:
